### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by robinbortlik** [14113/fio_api#13]
Hi @14113 , 

can you please release new version with update API domain to rubygems. I have no longer permission to do this. Thank you.

**Comment by 14113** [comment]
Done https://github.com/14113/fio_api/releases/tag/v0.0.8

**Comment by martinbarilik** [comment]
:100:  thanks, both of you

**Comment by martinbarilik** [comment]
One last thing missing, RubyGems.org :) 

.gemspec is not changed  therefore i suppose this is the last step to get it released
