### ISSUE TITLE
Release version tagged 0.0.8 to Rubygems.org

### ISSUE THREAD

**Issue by martinbarilik** [14113/fio_api#14]
Hi @14113 and @robinbortlik ,

can one of you push 0.0.8 to rubygems.org as mentioned in #13 ?

pretty please :) that'll be all regarding the matter

**Comment by robinbortlik** [comment]
Hi @martinbarilik , 

I'm very sorry, I did not realize I still have access to push to rubygems. 😞 My bad. 

New version has been released: https://rubygems.org/gems/fio_api

**Comment by martinbarilik** [comment]
no worries, glad it got sorted out :) thanks
